{% set name = "dataset" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataset-{{ version }}.tar.gz
  sha256: 037615522fe1c019e46af961036e6fe6fb051c9812dc95e1fb02fd80f98798d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - alembic >=0.6.2
    - banal >=1.0.2
    - python >=3.5
    - sqlalchemy >=1.3.2

test:
  imports:
    - dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pudo/dataset
  summary: Toolkit for Python-based database access.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - vasudevanv
